### PR TITLE
Possible solution to issue #25

### PR DESCRIPTION
**Pull request by dovrosenberg**
Made the proposed change noted in issue #25

### CODE REVIEW

**Comment by jchristman** [comment]
I cloned https://github.com/dovrosenberg/reactive-modal and when I ran it, I got the following error:

```
Exception in template helper: TypeError: Cannot read property 'get' of undefined
    at Object.Template._reactiveModal.helpers.disabled (http://10.13.0.164:3000/packages/pahans_reactive-modal.js?24f96b4ef16bcc2bed5a87484606e8db7a41d5ab:141:29)
    at http://10.13.0.164:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:2727:16
    at http://10.13.0.164:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:1606:16
    at Spacebars.call (http://10.13.0.164:3000/packages/spacebars.js?7f53771c84a2eafac2b561c9796dda0d8af8e7f5:171:18)
    at Spacebars.mustacheImpl (http://10.13.0.164:3000/packages/spacebars.js?7f53771c84a2eafac2b561c9796dda0d8af8e7f5:108:25)
    at Object.Spacebars.attrMustache (http://10.13.0.164:3000/packages/spacebars.js?7f53771c84a2eafac2b561c9796dda0d8af8e7f5:124:39)
    at http://10.13.0.164:3000/packages/pahans_reactive-modal.js?24f96b4ef16bcc2bed5a87484606e8db7a41d5ab:102:24
    at Object.Blaze._withCurrentView (http://10.13.0.164:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:2043:12)
    at Blaze._HTMLJSExpander.def.visitAttributes (http://10.13.0.164:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:1962:21)
    at HTML.TransformingVisitor.def.visitAttributes (http://10.13.0.164:3000/packages/htmljs.js?567eb96d5d22631c03d6aca6afa4c42f0d1295f2:202:44)
```

The problem exists on [line 16](https://github.com/dovrosenberg/reactive-modal/blob/5955eb29bf0f0057ec56c27ca6c5c191306701d6/lib/reactive-modal.js#L16) in the helpers 'disabled' function.

It appears you removed the ```newButton.disabled = ``` from [line 53](https://github.com/dovrosenberg/reactive-modal/blob/5955eb29bf0f0057ec56c27ca6c5c191306701d6/lib/reactive-modal.js#L53) of the code, so it just creates the variable but does not assign it to the disabled function. Should be a quick fix.

**Comment by jchristman** [comment]
I just fixed that in my local clone, and I can confirm that adding back ```newButton.disabled = ``` will fix the error and address issue #25.

**Comment by dovrosenberg** [comment]
Whoa - sorry about that; not sure how I pulled that off.  Thanks!

**Comment by jchristman** [comment]
@pahans I just verified its error-free operation in one of my own applications. I think you're good to merge it.

**Pull request merged**
